// Final delivered motion affordance: size, keyboard, dismissal and invariants.
const {chromium}=require('/tmp/node_modules/playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url');
const root=__dirname,url=pathToFileURL(path.join(root,'dist/index.html')).href,baseline=pathToFileURL(process.env.WATERFALL_V3_BASELINE||'/tmp/waterfall-v3-delivery.html').href;
let browser;const results=[];
async function box(p,selector){return p.locator(selector).evaluate(e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height};});}
async function disclosure(p){const c=await p.context().newCDPSession(p),d=await c.send('DOM.getDocument'),q=await c.send('DOM.querySelector',{nodeId:d.root.nodeId,selector:'#motion-toggle'}),a=await c.send('Accessibility.getPartialAXTree',{nodeId:q.nodeId}),n=a.nodes[0];const result={role:n.role.value,name:n.name.value,expanded:n.properties.find(x=>x.name==='expanded').value.value};await c.detach();return result;}
function contained(r,w,h){assert(r.x>=0&&r.y>=0&&r.x+r.width<=w+1&&r.y+r.height<=h+1,'Panel/control outside viewport '+JSON.stringify(r));}
function rgb(s){return s.match(/[\d.]+/g).map(Number);}
function luminance(c){return c.slice(0,3).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4}).reduce((n,v,i)=>n+v*[.2126,.7152,.0722][i],0);}
function contrast(a,b){const x=luminance(a),y=luminance(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05);}
(async()=>{browser=await chromium.launch({executablePath:'/home/theoses/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome',args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader-webgl','--enable-unsafe-swiftshader','--disable-gpu-sandbox']});
for(const [width,height,dpr] of [[1440,900,2],[390,844,3],[320,740,2],[667,375,2]]){
 const context=await browser.newContext({viewport:{width,height},deviceScaleFactor:dpr,reducedMotion:'no-preference'}),old=await context.newPage();await old.goto(baseline);await old.evaluate(()=>document.fonts.ready);await old.waitForFunction(()=>waterfallPreview?.state().ready);const before=await box(old,'#preview-controls');await old.close();
 const p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url);await p.evaluate(()=>document.fonts.ready);await p.waitForFunction(()=>waterfallPreview?.state().ready&&waterfallPreview.state().draws>1);assert.equal(await p.locator('body').getAttribute('data-motion-controls'),'compact-v4');assert(!(await p.locator('#motion-panel').isVisible()));const after=await box(p,'#preview-controls');contained(after,width,height);assert(after.height<before.height);assert(after.width*after.height<before.width*before.height*.75,'Not meaningfully smaller');
 const actions={};for(const selector of ['#pause','#motion-toggle']){const b=await box(p,selector);assert(b.width>=44&&b.height>=44);contained(b,width,height);actions[selector]=b;}
 const cs=await p.locator('#preview-controls').evaluate(el=>{const s=getComputedStyle(el),a=getComputedStyle(document.getElementById('pause'));return {bg:s.backgroundColor,fg:a.color};});const bg=rgb(cs.bg),whiteBound=bg.slice(0,3).map(v=>v*(bg[3]??1)+255*(1-(bg[3]??1)));const ratio=contrast(rgb(cs.fg),whiteBound);assert(ratio>=4.5);
 await p.locator('#pause').click();assert((await p.evaluate(()=>waterfallPreview.state())).paused);assert.equal(await p.locator('#pause').getAttribute('aria-pressed'),'true');await p.locator('#pause').click();assert(!(await p.evaluate(()=>waterfallPreview.state())).paused);
 await p.locator('#motion-toggle').focus();await p.keyboard.press('Enter');assert.deepEqual(await disclosure(p),{role:'DisclosureTriangle',name:'Motion',expanded:true});assert(await p.locator('#motion-status').isVisible());assert.match(await p.locator('#motion-status').innerText(),/Simulated water.*not a video loop/);contained(await box(p,'#motion-panel'),width,height);const stillBox=await box(p,'#still');assert(stillBox.width>=44&&stillBox.height>=44);
 await p.keyboard.press('Tab');assert(await p.locator('#still').evaluate(e=>e===document.activeElement));await p.keyboard.press('Enter');await p.waitForFunction(()=>waterfallPreview.state().staticView);assert.deepEqual((await p.evaluate(()=>waterfallPreview.state())).camera,[.5,.5,1]);assert.equal(await p.locator('#still').getAttribute('aria-pressed'),'true');await p.keyboard.press('Enter');await p.waitForFunction(()=>!waterfallPreview.state().staticView);
 await p.screenshot({path:path.join(root,'evidence',`controls-open-${width}.png`)});await p.keyboard.press('Escape');assert(!(await p.locator('#motion-panel').isVisible()));assert(await p.locator('#motion-toggle').evaluate(e=>e===document.activeElement));await p.locator('#motion-toggle').click();await p.locator('#intro h1').click();assert(!(await p.locator('#motion-panel').isVisible()));await p.locator('#motion-toggle').click();await p.locator('header>a').focus();assert(!(await p.locator('#motion-panel').isVisible()));assert.deepEqual(await disclosure(p),{role:'DisclosureTriangle',name:'Motion',expanded:false});
 await p.screenshot({path:path.join(root,'evidence',`controls-closed-${width}.png`)});assert.equal(errors.length,0,errors.join('\n'));results.push({width,height,dpr,before,after,areaFraction:after.width*after.height/(before.width*before.height),minimumTouchSize:44,whiteBackdropTextContrast:ratio,keyboardStill:true,escapeOutsideFocusDismissal:true,noErrors:true});await context.close();
}
fs.writeFileSync(path.join(root,'evidence/controls-results.json'),JSON.stringify(results,null,2));for(const x of results)console.log('PASS compact motion controls',JSON.stringify(x));await browser.close();})().catch(async e=>{console.error(e);await browser?.close();process.exit(1)});
