// Exercise the exact self-contained delivery artifact; no production requests.
const {chromium}=require('/tmp/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {pathToFileURL}=require('node:url');
const root=__dirname,url=pathToFileURL(path.join(root,'dist/index.html')).href;
const exe='/home/theoses/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome';
const log=[];let browser;
async function animationFrames(page,n=12){await page.evaluate(n=>new Promise(resolve=>{let count=0;function step(){if(++count>=n)resolve();else requestAnimationFrame(step);}requestAnimationFrame(step);}),n);}
async function ready(page){await page.goto(url);await page.evaluate(()=>document.fonts.ready);await page.waitForFunction(()=>window.waterfallPreview?.state().ready);await page.waitForFunction(()=>window.waterfallPreview.state().draws>1);}
(async()=>{
 browser=await chromium.launch({executablePath:exe,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader-webgl','--enable-unsafe-swiftshader','--disable-gpu-sandbox']});
 for(const [name,width,height] of [['desktop',1440,900],['mobile',390,844],['small-mobile',320,740]]){
  const ctx=await browser.newContext({viewport:{width,height},reducedMotion:'no-preference'});const page=await ctx.newPage();const errors=[];
  page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',route=>{const u=route.request().url();assert(/^(file:|data:|blob:)/.test(u),'Unexpected runtime network request '+u);return route.continue();});
  await ready(page);await page.evaluate(()=>document.documentElement.style.scrollBehavior='auto');
  assert.equal(await page.locator('meta[name="robots"]').getAttribute('content'),'noindex,nofollow');
  assert.equal(await page.locator('h1').innerText(),'Less work around work.\nMore room for business.');
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Horizontal overflow '+name);
  await page.screenshot({path:path.join(root,'evidence',name+'-hero.png')});
  if(name==='desktop'){
   // Compare actual GPU pixels while camera is fixed. Water must move, rocks must not.
   await page.evaluate(()=>{const c=document.getElementById('water');const g=c.getContext('webgl');const p=new Uint8Array(c.width*c.height*4);g.readPixels(0,0,c.width,c.height,g.RGBA,g.UNSIGNED_BYTE,p);window.pixelBefore=p;window.timeBefore=waterfallPreview.state().time;});
   await page.waitForFunction(()=>waterfallPreview.state().time>window.timeBefore+.7);
   const evidence=await page.evaluate(async()=>{const c=document.getElementById('water'),g=c.getContext('webgl'),p=new Uint8Array(c.width*c.height*4);g.readPixels(0,0,c.width,c.height,g.RGBA,g.UNSIGNED_BYTE,p);const maskSrc=document.querySelector('script').textContent.match(/maskURI='([^']+)'/)[1];const im=new Image();im.src=maskSrc;await im.decode();const mc=document.createElement('canvas');mc.width=im.width;mc.height=im.height;const mg=mc.getContext('2d');mg.drawImage(im,0,0);const mask=mg.getImageData(0,0,mc.width,mc.height).data;const cam=waterfallPreview.state().camera,cover=Math.max(innerWidth/im.width,innerHeight/im.height),ww=innerWidth/(im.width*cover*cam[2]),wh=innerHeight/(im.height*cover*cam[2]),cx=Math.max(ww/2,Math.min(1-ww/2,cam[0])),cy=Math.max(wh/2,Math.min(1-wh/2,cam[1]));let water=0,waterChanged=0,rock=0,rockChanged=0;for(let y=0;y<c.height;y+=3)for(let x=0;x<c.width;x+=3){const uvx=cx+((x+.5)/c.width-.5)*ww,uvy=cy+(.5-(y+.5)/c.height)*wh;const mx=Math.floor(uvx*im.width),my=Math.floor(uvy*im.height),mi=(my*im.width+mx)*4,pi=(y*c.width+x)*4;const diff=Math.abs(p[pi]-pixelBefore[pi])+Math.abs(p[pi+1]-pixelBefore[pi+1])+Math.abs(p[pi+2]-pixelBefore[pi+2]);if(mask[mi]>150){water++;if(diff>2)waterChanged++;}else if(mask[mi]<1&&mask[mi+1]<1){rock++;if(diff>2)rockChanged++;}}return {water,waterChanged,rock,rockChanged};});
   assert(evidence.waterChanged>100,'No measurable water flow '+JSON.stringify(evidence));assert(evidence.rockChanged<evidence.rock*.01,'Rock motion '+JSON.stringify(evidence));log.push({test:'actual water-only GPU pixel changes',...evidence});
  }
  await page.locator('#pause').click();let paused=await page.evaluate(()=>waterfallPreview.state());assert(paused.paused);await animationFrames(page);assert.equal((await page.evaluate(()=>waterfallPreview.state())).time,paused.time);
  const cameraBefore=paused.camera;await page.evaluate(()=>scrollTo(0,(document.documentElement.scrollHeight-innerHeight)*.53));await animationFrames(page);const mid=await page.evaluate(()=>waterfallPreview.state());assert.notDeepEqual(mid.camera,cameraBefore);assert.equal(mid.time,paused.time);await page.screenshot({path:path.join(root,'evidence',name+'-middle.png')});
  await page.evaluate(()=>scrollTo(0,document.documentElement.scrollHeight));await animationFrames(page);const bottom=await page.evaluate(()=>waterfallPreview.state());assert.equal(bottom.progress,1);assert(bottom.camera[1]>.7);await page.screenshot({path:path.join(root,'evidence',name+'-pool.png')});
  await page.locator('#still').click();await animationFrames(page);assert.deepEqual((await page.evaluate(()=>waterfallPreview.state())).camera,[.5,.5,1]);await page.evaluate(()=>scrollTo(0,0));await animationFrames(page);assert.deepEqual((await page.evaluate(()=>waterfallPreview.state())).camera,[.5,.5,1]);
  await page.locator('#still').click();await page.locator('#pause').click();assert.equal((await page.evaluate(()=>waterfallPreview.state())).paused,false);const t=await page.evaluate(()=>waterfallPreview.state().time);await page.waitForFunction(t=>waterfallPreview.state().time>t+.1,t);
  // Keyboard and normal anchor navigation.
  await page.locator('header a[href="#work"]').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>Math.abs(document.getElementById('work').getBoundingClientRect().top)<3);assert.equal(await page.locator('#work h2').innerText(),'Know what needs buying.\nKeep purchasing organised.');
  assert.equal(await page.locator('.index li a').count(),8);assert.equal(await page.locator('a[href="mailto:kisame350@gmail.com"]').count(),3);
  assert.equal(errors.length,0,errors.join('\n'));log.push({test:name+' real artifact: load, no overflow/network/errors, pause, resume, scroll-camera, still, keyboard, 8 links',pass:true});await ctx.close();
 }
 const rctx=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});const rp=await rctx.newPage();await rp.goto(url);await rp.waitForFunction(()=>waterfallPreview?.state().ready);await animationFrames(rp);const rs=await rp.evaluate(()=>waterfallPreview.state());assert(rs.staticView);assert.equal(rs.time,0);assert(await rp.locator('#pause').isDisabled());assert(await rp.locator('#still').isDisabled());await rp.evaluate(()=>scrollTo(0,document.documentElement.scrollHeight));await animationFrames(rp);assert.deepEqual((await rp.evaluate(()=>waterfallPreview.state())).camera,[.5,.5,1]);await rp.screenshot({path:path.join(root,'evidence/reduced-motion.png')});log.push({test:'reduced motion: water and camera both static',pass:true});await rctx.close();
 for(const mode of ['no-js','no-webgl']){const ctx=await browser.newContext({viewport:{width:390,height:844},javaScriptEnabled:mode!=='no-js'});if(mode==='no-webgl')await ctx.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return type==='webgl'?null:original.call(this,type,...args);};});const page=await ctx.newPage();await page.goto(url);await page.evaluate(()=>document.fonts.ready);assert(await page.locator('#fallback').evaluate(i=>i.complete&&i.naturalWidth===1920));assert(await page.locator('#intro h1').isVisible());await page.screenshot({path:path.join(root,'evidence/'+mode+'.png')});log.push({test:mode+': real image and text retained',pass:true});await ctx.close();}
 fs.writeFileSync(path.join(root,'evidence/qa-results.json'),JSON.stringify(log,null,2));for(const row of log)console.log('PASS',JSON.stringify(row));await browser.close();
})().catch(async e=>{console.error(e);await browser?.close();process.exit(1)});
