// Verify the actual public delivery, including native-density overlay and crop.
const {chromium}=require('/tmp/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');let browser;
(async()=>{browser=await chromium.launch({executablePath:'/home/theoses/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome',args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader-webgl','--enable-unsafe-swiftshader','--disable-gpu-sandbox']});const results=[];
for(const [width,height,dpr] of [[1440,900,2],[390,844,3],[320,740,2]]){
 const p=await browser.newPage({viewport:{width,height},deviceScaleFactor:dpr,reducedMotion:'no-preference'});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('https://image.wasabietech.com/portfolio-waterfall-preview/?v=4');await p.waitForFunction(()=>waterfallPreview?.state().ready&&waterfallPreview.state().draws>2);
 const e=await p.evaluate(()=>{const c=document.getElementById('water'),i=document.getElementById('fallback'),s=waterfallPreview.state();const card=document.querySelector('.reading'),cs=getComputedStyle(card);return{motionControls:document.body.dataset.motionControls,cardTreatment:document.body.dataset.cardTreatment,cardBackground:cs.backgroundColor,cardBlur:cs.backdropFilter,cardOpacity:cs.opacity,revision:s.revision,source:[i.naturalWidth,i.naturalHeight],canvas:[c.width,c.height],native:[Math.round(innerWidth*devicePixelRatio),Math.round(innerHeight*devicePixelRatio)],zoom:s.camera[2],nativePhotoPlaced:!!i.style.left,photoTop:i.style.top,css:Object.fromEntries(['#pause','#still','#motion-toggle','#motion-status','.disclosure'].map(s=>[s,getComputedStyle(document.querySelector(s)).fontSize]))};});
 assert.equal(e.motionControls,'compact-v4');assert.equal(e.cardTreatment,'moss-glass-v3');assert.equal(e.cardBackground,'rgba(35, 46, 30, 0.78)');assert.equal(e.cardBlur,'blur(12px)');assert.equal(e.cardOpacity,'1');assert.equal(e.revision,'directional-water-v2');assert.deepEqual(e.source,[1920,1280]);assert.deepEqual(e.canvas,e.native);assert(e.zoom<=1.18);assert(e.nativePhotoPlaced);for(const x of Object.values(e.css))assert.equal(x,'12px');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await p.locator('#pause').click();assert((await p.evaluate(()=>waterfallPreview.state())).paused);await p.evaluate(()=>{document.documentElement.style.scrollBehavior='auto';scrollTo(0,document.documentElement.scrollHeight)});await p.waitForFunction(()=>document.getElementById('scene-label').textContent==='Jade pool');assert.notEqual(await p.locator('#fallback').evaluate(i=>i.style.top),e.photoTop);await p.locator('#motion-toggle').click();assert(await p.locator('#motion-status').isVisible());await p.locator('#still').click();await p.waitForFunction(()=>waterfallPreview.state().staticView);assert.deepEqual((await p.evaluate(()=>waterfallPreview.state())).camera,[.5,.5,1]);assert.equal(errors.length,0,errors.join('\n'));results.push({width,height,dpr,publicHTML:true,pauseScrollStillPassed:true,...e});await p.close();
}
fs.writeFileSync(path.join(__dirname,'evidence/public-results.json'),JSON.stringify(results,null,2));for(const x of results)console.log('PASS actual public browser',JSON.stringify(x));await browser.close();})().catch(async e=>{console.error(e);await browser?.close();process.exit(1)});
