// Verified portfolio content. Never import production records into this module.
module.exports = [
  {
    slug:'procura', title:'Procura', category:'Procurement software',
    summary:'Know what needs buying. Keep purchasing organised.',
    description:'Inventory, suppliers, reorder planning and purchase orders in one connected application.',
    problem:'Stock levels, supplier information and purchasing decisions are difficult to follow when they live in separate spreadsheets and conversations.',
    built:'I built a procurement application that connects inventory, suppliers, purchase orders, requests for quotation and planning. It brings the buying workflow into one place instead of treating each document as a separate task.',
    workflow:['Review stock and reorder points','Plan purchases by supplier','Draft and review orders','Track the purchasing history'],
    implementation:'Go serves the web interface and embeds its assets in a single binary. SQLite keeps the inventory and purchasing records together. Spreadsheet import and unit-of-measure mappings support existing operational data.',
    limits:'The screenshots use a separate seeded demo database. No supplier is contacted and no purchase is submitted from this portfolio. Operational records and client results are not published here.',
    stack:['Go','SQLite','Embedded web UI'],
    featured:true, preview:'procura-inventory.webp', previewAlt:'Actual Procura inventory interface with fictional seeded records',
    disclosure:'Actual Procura UI; isolated fictional demo records.',
    scenes:[['Inventory','procura-inventory.webp','See stock levels and reorder points before deciding what to buy.'],['Planning','procura-planning.webp','Review reorder planning alongside a fictional stock list.'],['Purchase orders','procura-orders.webp','Follow the order workflow using fictional suppliers and sample amounts.']],
    evidence:['Procura repository README','Existing Procura case study','CAPTURE-PROVENANCE.json']
  },
  {
    slug:'pims', title:'PIMS', category:'Inventory operations',
    summary:'Give stock requests a clear place to go.',
    description:'Procurement and inventory workflows for a veterinary hospital, from internal requests to receipt and stock take.',
    problem:'A team needs to request stock, review it and record what arrived without losing the handover between departments.',
    built:'I built PIMS around internal indents, department purchase orders, approval queues, goods receipt, stock take, disposal and expiry tracking. The system also supports item specification requests and master-data administration.',
    workflow:['Raise an internal request','Review and approve','Track the order and receipt','Record stock activity'],
    implementation:'A Go application serves a single-page web interface and stores workflow data in PostgreSQL. It reads current stock quantities from Procura’s SQLite database without keeping a second editable stock balance.',
    limits:'These are genuine interface captures rendered with local fictional responses, not a live application. PIMS does not change Procura-owned stock quantities. PDF generation for GRNs, PRFs and analysis reports is not currently included.',
    stack:['Go','PostgreSQL','Read-only stock integration'],
    source:'https://github.com/H4fizWasabie/pims',
    disclosure:'Actual PIMS UI; local fictional sample responses.',
    scenes:[['Dashboard','pims-dashboard.webp','See pending requests and workflow summaries in one place.'],['Indent request','pims-request.webp','Inspect the request form with a fictional item and quantity.'],['Order tracking','pims-orders.webp','See order, payment and receipt stages in the real interface.']],
    evidence:['H4fizWasabie/pims README at b5148cfa7f3029fb91ea9d4b0da1e0a8b23f219b','CAPTURE-PROVENANCE.json']
  },
  {
    slug:'dd-drugs-register', title:'DD Drugs Register', category:'Clinical recordkeeping',
    summary:'Make daily counts accountable.',
    description:'A hospital dangerous-drugs register that compares physical and system counts while preserving the record.',
    problem:'A daily count needs a clear owner, an explicit discrepancy and a correction history that does not erase the original entry.',
    built:'I built a multi-user daily register with physical-versus-system counts, discrepancy flags, audited corrections and CSV export. Original entries remain in the ledger when a correction is made.',
    workflow:['Enter the daily physical count','Compare with the system count','Identify any discrepancy','Record a correction with a reason'],
    implementation:'Go and SQLite provide a compact application and a persistent register. Corrections reference the original entry instead of replacing it. Multi-user login makes entries attributable.',
    limits:'Drug names, storage locations, quantities and staff records stay private. This page shows a workflow outline, not the hospital interface or a compliance certification. The source repository is private.',
    stack:['Go','SQLite','Audited corrections'],
    disclosure:'Workflow outline only; no clinical records shown.', scenes:[],
    evidence:['Private DD Drugs Record README at c6aae2ce6cad52da24534d1817a1441b38760c8b','Existing DD Drugs Register case study']
  },
  {
    slug:'theoses', title:'Theoses', category:'AI assistant & coding agent',
    summary:'Turn repeated tasks into reviewable workflows.',
    description:'A self-hosted personal assistant and coding agent, available through the terminal, Telegram and a private dashboard.',
    problem:'Research, files, reports and code changes need continuity across conversations—and important actions still need human review.',
    built:'I built Theoses to work in real projects: read and edit files, run commands, research questions and use extensions. Persisted sessions, working notes and durable memory help carry context between tasks.',
    workflow:['Ask about a real workspace','Inspect files and evidence','Prepare a draft or change','Review before consequential action'],
    implementation:'A Node.js and TypeScript runtime powers the terminal, Telegram and dashboard channels. Its tool loop can be extended with skills, providers and integrations. Channel sessions and durable memory serve different roles.',
    limits:'The images are staged sample conversations in the genuine dashboard, not live AI execution. The portfolio sends no messages, creates no orders and changes no files. The agent itself is not a filesystem or network sandbox.',
    stack:['Node.js','TypeScript','Tool integrations'],
    source:'https://github.com/H4fizWasabie/theoses2',
    featured:true, preview:'theoses-report.webp', previewAlt:'Genuine Theoses dashboard showing an explicitly staged fictional conversation',
    disclosure:'Actual Theoses dashboard; staged sample conversation, not live execution.',
    scenes:[['Draft report','theoses-report.webp','Inspect a clearly staged stock-report conversation and fictional draft.'],['Review draft','theoses-review.webp','See the draft in review mode. No message or order is sent.']],
    evidence:['H4fizWasabie/theoses2 README at 27f0957a37297e286ea1cfca11be70ae3878cd69','CAPTURE-PROVENANCE.json']
  },
  {
    slug:'yen', title:'Yen', category:'Go AI agent',
    summary:'Carry the assistant into a compact Go runtime.',
    description:'A Go implementation of the Theoses agent architecture, with conversation continuity and memory across channels.',
    problem:'An assistant should retain a conversation’s identity when its owner moves between a terminal, Telegram and a browser.',
    built:'I built Yen as a Go agent with a canonical conversation model, shared memory and channel adapters. Its implementation is developed against documented TypeScript behavior rather than treating a similar-looking interface as compatibility.',
    workflow:['Enter through a channel','Resolve the canonical conversation','Run the agent and its tools','Persist the conversation and memory'],
    implementation:'The Go runtime separates channel adapters, conversation identity, model providers, tools and memory. Repository contracts and parity reports record implemented behavior and remaining differences.',
    limits:'Yen is a separate Go implementation, not a claim that it has replaced Theoses or achieved complete feature parity. This page shows an architecture outline, not a running agent or an invented chat.',
    stack:['Go','Conversation persistence','Shared memory'],
    source:'https://github.com/H4fizWasabie/yen',
    disclosure:'Architecture outline; no live agent session shown.', scenes:[],
    evidence:['H4fizWasabie/yen AGENTS.md and CONTEXT.md at b50c94a0efba4658c76e878654ee98b10ca0f388','Yen M10 parity report and handoff']
  },
  {
    slug:'map', title:'MAP', category:'Local-first Android app',
    summary:'Keep everyday tools together, on your phone.',
    description:'Tasks, calendar, documents, scan-to-PDF and local music in one personal Android utility.',
    problem:'Everyday organisation can mean moving between unrelated tools—even when the task and the files are already on the phone.',
    built:'I built MAP (My Awesome App) around a Home/Today view, with tasks and calendar scheduling, a document shelf, scan-to-PDF and local music. I use it on my own phone.',
    workflow:['Check the Home/Today view','Plan tasks in the calendar','Keep local documents together','Use scanning and local music'],
    implementation:'A native Kotlin Android app with on-device state. There is no account, backend, analytics or cloud sync. The source and sideload APK releases are available on GitHub.',
    limits:'These owner-approved phone captures have fictional text substituted for private activity, filenames and music details. They are edited screenshots, not a populated demo installation. APK releases are debug-signed; this is personal-use software, not a claimed Play Store release or public-adoption result.',
    stack:['Kotlin','Android','On-device data'],
    source:'https://github.com/H4fizWasabie/map-android', releases:'https://github.com/H4fizWasabie/map-android/releases',
    featured:true, preview:'map-overview.webp', previewAlt:'Composite of three genuine MAP phone screenshots: Home, Tasks and Tools, with fictional text',
    disclosure:'Edited MAP phone screenshots; fictional demo text. Original app layout retained.',
    scenes:[['Home','map-home-demo.webp','See Home/Today, music and recent activity with fictional text.'],['Calendar','map-calendar-demo.webp','Inspect the calendar view; no fictional appointments were added.'],['Tasks','map-tasks-demo.webp','See the task screen and fictional completed activity.'],['Tools','map-tools-demo.webp','Explore the real appearance choices and document list with safe filenames.']],
    evidence:['H4fizWasabie/map-android README at ef07c3295bd0e3e7dc0621564044082c22d5409d','Owner daily-use confirmation and screenshot approval, 2026-10-03','MAP-CAPTURE-PROVENANCE.json']
  },
  {
    slug:'hills-ai-content-lab', title:'Hill’s AI Content Lab', category:'AI-assisted content',
    summary:'Turn product information into a clear content story.',
    description:'A self-directed nutrition-content project connecting research, AI-assisted drafts and structured editorial review.',
    problem:'A product range can overwhelm its audience unless the facts are translated into useful questions and a coherent message.',
    built:'I developed a pet-nutrition content concept from supplied product material. One message is adapted into a post, carousel and story, with checkpoints for wording, tone, audience fit and the next action.',
    workflow:['Research the supplied material','Shape one content idea','Adapt it across formats','Review wording and audience fit'],
    implementation:'The project uses research, AI-assisted generation, structured checkpoints and content management. Its “Start with the clue” idea becomes a hook, an educational sequence and an invitation to reply.',
    limits:'This is a self-directed, unaffiliated content concept, not commissioned Hill’s client work. Hill’s is a trademark of its owner. No campaign performance or conversion results are claimed, and supplied product photography is not claimed as my work.',
    stack:['Content strategy','AI-assisted drafting','Editorial review'],
    outputs:[['Post','Every pet has a clue.','Begin with a useful question before introducing product choices.'],['Carousel','Look for the clue.','Organise the story around age, size, lifestyle and the owner’s concern.'],['Story','Tell us the clue.','Invite a question or reply instead of inventing a campaign result.']],
    disclosure:'Original content concept; self-directed and unaffiliated.', scenes:[],
    evidence:['Existing Hill’s AI Content Lab case study and content concept']
  },
  {
    slug:'89lab', title:'89lab content automation', category:'Publishing & video pipelines',
    summary:'Give repeated content production a reliable path.',
    description:'A family of publishing and narrated-video workflows, grouped as one automation case study.',
    problem:'Research, writing, voiceover, captions, rendering and publishing become fragile when every handover is manual or untracked.',
    built:'I connected content workspaces into repeatable pipelines. The YouTube Shorts workflow selects a topic, prepares a script, creates voiceover and timed captions, renders the video, verifies the upload and records its outcome.',
    workflow:['Select a topic and prepare the script','Produce voiceover, captions and video','Verify and publish the media','Record the outcome and prevent duplicates'],
    implementation:'Workspace runners coordinate staged outputs and ledgers. Local Kokoro speech, caption timing and FFmpeg rendering handle media production; publishing integrations verify the transferred media. Quota failures can hand the finished video back for manual posting.',
    limits:'This page explains the implemented pipeline without running it. No posts are published from the portfolio, no account credentials are exposed and no audience-growth claims are invented. The separate publishing jobs remain unchanged.',
    stack:['Python & shell','Kokoro TTS','FFmpeg','Publishing integrations'],
    disclosure:'Workflow outline; no publishing action is triggered.', scenes:[],
    evidence:['ai-agent-shorts/AGENTS.md, read 2026-10-03','Owner-approved grouping of publishing/video workflows as 89lab']
  }
];
